name: legal_text_app
description: A legal text summarizer and anonymizer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.5
  http: ^1.3.0
  url_launcher: ^6.1.5
  flutter_spinkit: ^5.1.0
  path_provider: ^2.0.11
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png  # Add your robot icon here